apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "perforator.fullname" . }}-pod-lister
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "perforator.fullname" . }}-pod-lister
subjects:
- kind: ServiceAccount
  name: {{ include "perforator.fullname" . }}
  namespace: {{ .Release.Namespace }}